src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pseudo = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\ManyToMany(targetEntity: Gif::class, inversedBy: 'voters')]
    #[ORM\JoinTable(name: 'vote')]
    private Collection $vote;

    #[ORM\ManyToMany(targetEntity: Gif::class, inversedBy: 'collectors')]
    #[ORM\JoinTable(name: 'collection')]
    private Collection $collection;

    public function __construct()
    {
        $this->vote = new ArrayCollection();
        $this->collection = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(?string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, Gif>
     */
    public function getVotes(): Collection
    {
        return $this->vote;
    }

    public function addToVotes(Gif $vote): self
    {
        if (!$this->vote->contains($vote)) {
            $this->vote->add($vote);
        }

        return $this;
    }

    public function removeFromVotes(Gif $vote): self
    {
        $this->vote->removeElement($vote);

        return $this;
    }

    /**
     * @return Collection<int, Gif>
     */
    public function getCollection(): Collection
    {
        return $this->collection;
    }

    public function addToCollection(Gif $collection): self
    {
        if (!$this->collection->contains($collection)) {
            $this->collection->add($collection);
        }

        return $this;
    }

    public function removeFromCollection(Gif $collection): self
    {
        $this->collection->removeElement($collection);

        return $this;
    }

    public function isInCollection(Gif $gif): bool
    {
        if ($this->getCollection()->contains($gif)) {
            return true;
        }
        return false;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email', EmailType::class, [
                'attr' => [
                    'placeholder' => 'Ex : k.malone@aol.com',
                    'maxlength' => 255,
                    'class' => 'crud-input',
                ],
                'label_attr' => [
                    'class' => 'crud-label',
                ],
                'required' => true,
                'label' => 'Mail :',
            ])

            ->add('roles', ChoiceType::class, [
                'choices' => [
                    'Utilisateur' => 'ROLE_USER',
                    'Administrateur' => 'ROLE_ADMIN',
                ],
                'multiple' => true,
                'expanded' => false,
            ])

            ->add('pseudo', TextType::class, [
                'attr' => [
                    'placeholder' => 'Ex : GifFan',
                    'maxlength' => 255,
                ],
                'required' => false,
                'label' => 'Pseudo :',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[IsGranted('ROLE_ADMIN')]
#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/', name: 'app_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, UserRepository $userRepository): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->save($user, true);

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, UserRepository $userRepository): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->save($user, true);

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, UserRepository $userRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $user->getId(), $request->request->get('_token'))) {
            $userRepository->remove($user, true);
        }

        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
	<button class="btn btn-danger mt-3">Delete</button>
</form>

templates/user/_form.html.twig
{% form_theme form 'bootstrap_5_layout.html.twig' %}

{{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn btn-primary originalbtn col-1">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}Edit User
{% endblock %}

{% block body %}
	<main class="m-3">
		<h1>Edit User</h1>

		{{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

		{{ include('user/_delete_form.html.twig') }}

		<div class="mt-5">
			<a href="{{ path('app_user_index') }}">Back to list</a>
		</div>
	</div>
</main>{% endblock %}

templates/user/index.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}User index
{% endblock %}

{% block body %}
	<main class="m-3">
		<h1>User index</h1>

		<a class="btn btn-primary originalbtn col-1 my-4" href="{{ path('app_user_new') }}">Create new</a>

		<table class="table">
			<thead>
				<tr>
					<th>Id</th>
					<th>Email</th>
					<th>Roles</th>
					<th>Pseudo</th>
					<th>Collection</th>
					<th>GIFs Voted</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				{% for user in users %}
					<tr>
						<td>{{ user.id }}</td>
						<td>{{ user.email }}</td>
						<td>
							{% if 'ROLE_ADMIN' in user.roles %}
								ADMIN
							{% else %}
								USER
							{% endif %}
						</td>
						<td>{{ user.pseudo }}</td>
						<td>{{ user.collection|length }}</td>
						<td>{{ user.votes|length }}</td>

						<td>
							<a class="btn btn-primary originalbtn d-block mb-3" href=" {{ path('app_user_show', {'id': user.id} ) }}">Show</a>
							<a class="btn btn-secondary originalbtn d-block" href="{{ path('app_user_edit', {'id': user.id}) }}">Edit</a>
						</td>
					</tr>
				{% else %}
					<tr>
						<td colspan="7">no records found</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</main>


{% endblock %}

templates/user/new.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}New User
{% endblock %}

{% block body %}
	<main class="m-3">


		<div class="text-center m-auto">
			<h1>Create new User</h1>
			<h2 class="mt-5 fst-italic">
				Coming soon</h2>
			<img class="m-auto my-5" src="{{asset('build/images/ThatsWhatSheSaid.gif')}}" alt="">
			<div>
				<a href="{{ path('app_user_index') }}">Back to list</a>
			</div>
		</div>


	</main>

{% endblock %}

templates/user/show.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}Show User
{% endblock %}

{% block body %}
	<main class="m-3">

		<h1>User</h1>

		<table class="table">
			<tbody>
				<tr>
					<th>Id</th>
					<td>{{ user.id }}</td>
				</tr>
				<tr>
					<th>Email</th>
					<td>{{ user.email }}</td>
				</tr>
				<tr>
					<th>Roles</th>
					<td>{{ user.roles ? user.roles|json_encode : '' }}</td>
				</tr>
				<tr>
					<th>Pseudo</th>
					<td>{{ user.pseudo }}</td>
				</tr>
			</tbody>
		</table>

		<a class="btn btn-secondary originalbtn" href="{{ path('app_user_edit', {'id': user.id}) }}">Edit</a>

		{{ include('user/_delete_form.html.twig') }}

		<div class="mt-5">
			<a href="{{ path('app_user_index') }}">Back to list</a>
		</div>

	</main>
{% endblock %}